### ISSUE TITLE
Practica4_IrvingFernandoReyesPacheco

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-equipo-de-irving#1]
[Reporte de Practica 4.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-equipo-de-irving/files/9621341/Reporte.de.Practica.4.pdf)

**Comment by JudithReynaCS** [comment]
CALIFICACION:20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
